Add minor error checking to run scripts.

diff --git a/kms/scripts/run b/kms/scripts/run
--- a/kms/scripts/run
+++ b/kms/scripts/run
@@ -1,3 +1,24 @@
+# We require some files to be present to run this script successfully.
+# We're asserting that they are present so we can catch errors early.
+
+requiredFiles=(
+    config-service/target/config-service-0.0.1-SNAPSHOT.jar
+    registration-service/target/registration-service-0.0.1-SNAPSHOT.jar
+    auth-service/target/auth-service-0.0.1-SNAPSHOT.jar
+    kms-service/target/kms-service-0.0.1-SNAPSHOT.jar
+    kms-api-gateway/target/kms-api-gateway-0.0.1-SNAPSHOT.jar
+    kms-qnl-service/.mvnw
+    ../../qnl/key-routing-service/./mvnw
+    ../../qll_sim/.mvnw
+)
+
+for filePath in ${requiredFiles[@]}; do
+    if [ ! -f $filePath ]; then
+        echo "File $filePath not found"
+        exit 1
+    fi
+done
+
 mkdir -p ~/qkd_logs
 screen -Sdm config-svc java -jar config-service/target/config-service-0.0.1-SNAPSHOT.jar
 echo "Starting KMS config service..."
